package rix

import "fmt"

// Exception is a fundamental error generated by a [Func].
type Exception struct {
	Error error
}

// NewException creates an [*Exception] with the given reason string.
func NewException(format string, v ...any) *Exception {
	return &Exception{fmt.Errorf(format, v...)}
}
